In [1]:
#PANDAS: 
#Pandas is a library providing easy to use data structures and data analysis tools.

In [13]:
#Dataframe: is a combination of at least more than one row and at least more than one column

In [ ]:
#Series: can either be one row or be one column

In [3]:
import pandas as pd
import numpy as np

In [7]:
#Creating a dataframe
df= pd.DataFrame(np.arange(0,20).reshape(5,4),index=[1,2,3,4,5], columns=["A","B","C","D"])

In [9]:
df.head()

    A   B   C   D
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [10]:
#to convert the dataframe to a csv file
df.to_csv('testcsv')

In [11]:
df.loc[1]

A    0
B    1
C    2
D    3
Name: 1, dtype: int64

In [12]:
type(df.loc[1])

pandas.Series

In [16]:
df.iloc[0:2,0:2]
#left side is rows, right side is column

   A  B
1  0  1
2  4  5

In [17]:
type(df.iloc[0:2,0:2])

pandas.DataFrame

In [23]:
df.iloc[:,:]

    A   B   C   D
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [24]:
#converting dataframe to array
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
df.isnull().sum()

A    0
B    0
C    0
D    0
dtype: int64

In [28]:
#To find out the number of categories in a column
df["A"].value_counts()

A
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [29]:
#To find out only the unique values in a column
df["A"].unique

<bound method Series.unique of 1     0
2     4
3     8
4    12
5    16
Name: A, dtype: int64>